/** Delivery formats supported by the v0.2.1 promotional campaign. */
export type PromoFormat = "landscape" | "vertical"

/** Frames per second shared by every campaign delivery. */
export const PROMO_FPS = 30

/** Total campaign duration: 42 seconds. */
export const PROMO_DURATION_IN_FRAMES = 42 * PROMO_FPS

/** Named deterministic product captures generated by `pnpm promo:capture`. */
export const PRODUCT_SHOTS = {
  home: "captures/ai-review/home-ready.png",
  review: "captures/ai-review/review-diff.png",
  walkthrough: "captures/ai-review/walkthrough-critical.png",
  threadPending: "captures/ai-review/thread-pending.png",
  threadComplete: "captures/ai-review/thread-complete.png",
  revisionUpdated: "captures/ai-review/revision-updated.png",
  approved: "captures/ai-review/approved.png",
} as const

/** Camera offset applied to a product capture inside the staged app window. */
export interface ProductCamera {
  readonly scale: number
  readonly x: number
  readonly y: number
}

/** Format-specific camera presets for the primary campaign beats. */
export const PRODUCT_CAMERAS: Readonly<
  Record<PromoFormat, Readonly<Record<keyof typeof PRODUCT_SHOTS, ProductCamera>>>
> = {
  landscape: {
    home: { scale: 1, x: 0, y: 0 },
    review: { scale: 1.02, x: -8, y: -4 },
    walkthrough: { scale: 1.04, x: -18, y: -8 },
    threadPending: { scale: 1.08, x: -42, y: -52 },
    threadComplete: { scale: 1.08, x: -42, y: -52 },
    revisionUpdated: { scale: 1.06, x: -30, y: -34 },
    approved: { scale: 1.04, x: -18, y: -12 },
  },
  vertical: {
    home: { scale: 1.22, x: -40, y: 0 },
    review: { scale: 1.5, x: -470, y: -30 },
    walkthrough: { scale: 1.42, x: -250, y: -24 },
    threadPending: { scale: 1.58, x: -600, y: -100 },
    threadComplete: { scale: 1.58, x: -600, y: -100 },
    revisionUpdated: { scale: 1.5, x: -520, y: -70 },
    approved: { scale: 1.42, x: -430, y: -40 },
  },
}
