/** Canonical invoke channels shared by the Electron host and preload bridge. */
export const InvokeChannel = {
  analyticsCapture: "analytics:capture",
  analyticsStart: "analytics:start",
  agentProvidersGetCatalog: "agentProviders:getCatalog",
  appDiagnostics: "app:diagnostics",
  appInstallDiffDashCli: "app:installDiffDashCli",
  appActivateWindow: "app:activateWindow",
  appOpenExternalUrl: "app:openExternalUrl",
  appOpenLocalRepositoryFile: "app:openLocalRepositoryFile",
  appOpenRepositoryFile: "app:openRepositoryFile",
  appOpenRepositoryComparisonFile: "app:openRepositoryComparisonFile",
  appStateGet: "appState:get",
  appStateUpdate: "appState:update",
  listProviders: "providers:list",
  submitHostedReviewDecision: "hostedReviews:submitDecision",
  getHostedReviewDecision: "hostedReviews:getDecision",
  listHostedReviews: "hostedReviews:list",
  listAssignedHostedReviews: "hostedReviews:listAssigned",
  listHostedRepositorySearchScopes: "hostedRepositories:listSearchScopes",
  searchHostedRepositories: "hostedRepositories:search",
  resolveLocalBranch: "localReviews:resolveBranch",
  resolveLastCommit: "localReviews:resolveLastCommit",
  resolveRepositoryComparison: "repositoryComparisons:resolve",
  acquireHostedReviewSnapshot: "reviewSnapshots:acquireHosted",
  acquireLocalReviewSnapshot: "reviewSnapshots:acquireLocal",
  acquireRepositoryComparisonSnapshot: "reviewSnapshots:acquireRepositoryComparison",
  getReviewSnapshotPage: "reviewSnapshots:getPage",
  searchReviewSnapshot: "reviewSnapshots:search",
  generateLocalWalkthrough: "localWalkthroughs:generate",
  getLocalWalkthrough: "localWalkthroughs:get",
  generateRepositoryComparisonWalkthrough: "repositoryComparisonWalkthroughs:generate",
  getRepositoryComparisonWalkthrough: "repositoryComparisonWalkthroughs:get",
  drainNavigationCommands: "navigation:drainCommands",
  favoriteRemoteRepository: "repositories:favoriteRemote",
  forgetRepository: "repositories:forget",
  installRepository: "repositories:install",
  linkRepository: "repositories:link",
  listRepositories: "repositories:list",
  openProject: "repositories:openProject",
  repairRepositoryIdentities: "repositories:repairIdentities",
  selectLocalFolder: "repositories:selectLocalFolder",
  setRepositoryFavorite: "repositories:setFavorite",
  projectWorkspaceGet: "projectWorkspace:get",
  projectWorkspaceSave: "projectWorkspace:save",
  addReviewThreadUserMessage: "reviewThreads:addUserMessage",
  createReviewThread: "reviewThreads:create",
  getReviewThread: "reviewThreads:get",
  listReviewThreads: "reviewThreads:list",
  runReviewThreadAgent: "reviewThreads:runAgent",
  settingsGet: "settings:get",
  settingsUpdate: "settings:update",
  updatesCheck: "updates:check",
  updatesDownload: "updates:download",
  updatesGetState: "updates:getState",
  updatesRestartAndInstall: "updates:restartAndInstall",
  listViewedFiles: "viewedFiles:list",
  listLocalViewedFiles: "viewedFiles:listLocal",
  setViewedFile: "viewedFiles:set",
  setLocalViewedFile: "viewedFiles:setLocal",
  listRepositoryComparisonViewedFiles: "viewedFiles:listRepositoryComparison",
  setRepositoryComparisonViewedFile: "viewedFiles:setRepositoryComparison",
  generateWalkthrough: "walkthroughs:generate",
  getWalkthrough: "walkthroughs:get",
} as const

/** One valid renderer-to-host invoke channel. */
export type InvokeChannel = (typeof InvokeChannel)[keyof typeof InvokeChannel]

/** Canonical host-to-renderer event channels. */
export const EventChannel = {
  navigationCommandsAvailable: "navigation:commandsAvailable",
  reviewThreadAgentProgress: "reviewThreads:agentProgress",
  updateStateChanged: "updates:stateChanged",
} as const

/** One valid host-to-renderer event channel. */
export type EventChannel = (typeof EventChannel)[keyof typeof EventChannel]
